### ISSUE TITLE
It should be possible to orchestrate 2.2 servers

### ISSUE THREAD

**Issue by spencerjackson** [10gen/mongo-orchestration#152]
By default enableTestCommands is passed to all servers, but this prevents initialization of pre-2.4 servers. We would like to be able to bring up and test the C++ legacy driver against 2.2 servers, as per https://github.com/mongodb/mongo-cxx-driver/pull/214

**Comment by lovett89** [comment]
Mongo Orchestration automatically turns on/off enableTestCommands based on the server version as of 5125a334e9fdcae10d65300e5963fe3dd137c7e7
