### ISSUE TITLE
Creating Users -- with non-default authMechanism

### ISSUE THREAD

**Issue by bjori** [10gen/mongo-orchestration#156]
Using preset files you can provide MO with username and password to use for the initial user.

There is currently no way to tell MO what mechanism this user is supposed to use, or which database to create the user in.

Things get then more complicated when the deafult authMechanism is removed from mongod, as MO can no longer login as that user as it just doesn't support that authMechanism.

**Comment by lovett89** [comment]
MO supports the "default" auth mechanism + MONGODB-X509 as of 9aa35e28487ce87da61996a25c9dccbf1367ee98. It supports parsing the `authenticationMechanisms` parameter and specifying the auth source. This hasn't been tested with PLAIN or GSSAPI, though, but let's create new issues targeted at any unsupported auth mechanisms as we encounter them.
