### ISSUE TITLE
Return credentials pair as part of the connection string

### ISSUE THREAD

**Issue by bjori** [10gen/mongo-orchestration#157]
Currently server info returns the connection uri as
"mongodb_uri": "mongodb://localhost:1029",

When the server was created with authentication and intial user, it would be nice to get a fully authenticated connection string back:
"mongodb_auth_uri": "mongodb://username:password@localhost:1029/dbname?authMechanism=SCRAM-SHA-1",

**Comment by lovett89** [comment]
resolved in 2bccf6ebe77de0a902b8cfe5e239c7fa48d5b4dd
