### ISSUE TITLE
Allow server_id to be defined in replica set member config

### ISSUE THREAD

**Issue by estolfo** [10gen/mongo-orchestration#164]
It'd be great if you could define a server_id for a member in a replica set. For example, the payload for a POST request to /replica_sets would look like this:

    {
      "members": 
         [ {"rsParams": {"priority":1}, "server_id": "serverA",
           {"rsParams":  {"priority":0}, "server_id": "serverB",
           {"rsParams": {"arbiterOnly":true}, "server_id": "serverC",
         ]
    }

And then you could send commands (stop, start, restart) to the uri /servers/serverA

**Comment by lovett89** [comment]
Available as of 27a05cfcda8d3bf23fb22f4a329096effd3e59fd! The format for the requests is as you describe. For shards, replica set member ids may be given in the key `rs_id`. All server ids are given in `server_id`.

**Comment by estolfo** [comment]
sweet, thanks @lovett89 !!
