### ISSUE TITLE
put server logs in data directory by default

### ISSUE THREAD

**Issue by amidvidy** [10gen/mongo-orchestration#170]
Currently MO has servers log to stdout, then redirects all logging output to /dev/null by default. This makes it somewhat hard to give the server team any kind of useful debugging info when driver tests uncover server issues, which happens fairly regularly in drivers that test against nightlies. 

While this can be overriden, I think a more sane default would be put the log in a file called 'mongod.log' (or mongos.log if it is a mongos) in the data directory used by that server.

**Comment by lovett89** [comment]
resolved in be4aecc6cd6e94fa6ab8e71d3ce1c19d8631bde9. Note that `logappend` is not the default and still needs to be passed into `procParams`.
