### ISSUE TITLE
Allow configuring socketTimeoutMS

### ISSUE THREAD

**Issue by amidvidy** [10gen/mongo-orchestration#185]
On windows replSetInitiate can take quite a long time - sometimes over 30 seconds. This was causing MO to timeout in the C++ MCI suite when setting up replica sets. I can see that the default socketTimeoutMS passed to MongoClient is 2000 in replica_sets.py, which is too short for us. Would it be possible to allow us to set (or disable) socketTimeoutMS when creating a replica set?

**Comment by llvtt** [comment]
This can be configured with the `--socket-timeout-ms` option as of 4d5a0aa3d66cd43d33f4b453951c3adef3e6e8ec.
