### ISSUE TITLE
Support config server changes for MongoDB 3.1.x

### ISSUE THREAD

**Issue by behackett** [10gen/mongo-orchestration#191]
Config servers will be a replica set starting in MongoDB 3.2. The changes for https://jira.mongodb.org/browse/SERVER-18104 have already broken existing sharding test setup in Jenkins. This ticket is to track changes related to launching a 3.2 sharded cluster for testing.

**Comment by llvtt** [comment]
resolved in 2c4abbfb4babbc91222ac43290eb0f90929f2044
