### ISSUE TITLE
Add configurations for selecting the mmap storage engine

### ISSUE THREAD

**Issue by acmorrow** [10gen/mongo-orchestration#197]
Since mongodb master has now flipped the default storage engine to WT, there needs to be a way to explicitly request the MMAP storage engine, so that drivers can test against both when using the latest server versions.

**Comment by behackett** [comment]
Just a note - you can already already specify storageEngine in procParams. See an example here:

https://github.com/10gen/mongo-orchestration/blob/master/mongo_orchestration/configurations/servers/wiredtiger.json

But yes, we can add an explicit configuration file.

**Comment by acmorrow** [comment]
@behackett Thanks, that would be helpful, as it would make the changes we need to make in the C++ driver MCI config much simpler.

**Comment by llvtt** [comment]
There's a PR for this... does it include everything we need? #196

**Comment by llvtt** [comment]
Resolved in 5886837d621d5a01d684909ac5c3f23fc4150b54. There is now an `mmapv1.json` preset for all cluster types.
