### ISSUE TITLE
mongo-orchestration doesn't tell you when it fails to start

### ISSUE THREAD

**Issue by bjori** [10gen/mongo-orchestration#202]
The mongo-orchestration during startup is completely fake.

    child process started successfully, parent exiting after 5 seconds
    Starting Mongo Orchestration on port 8889...

The exit code is successful (0), but mongo-orchestration made no attempt to confirm that it actually launched successfully.

What is worse, the log file it created is completely empty.

Repro steps:
- cd /tmp
- mkdir mo{1,2}
- cd mo1
- mongo-orchestration start
- [wait 5 seconds]
- cd ../mo2
- mongo-orchestration start
- echo $?

The second log, `/tmp/mo2/server.log`, will be completely empty. The exit code will also be successful (0).
Not pid file is created though `\o/`

**Comment by llvtt** [comment]
resolved in f9c927c6bde3e0c847bdd5e898c8f05fd504fb3d
