### ISSUE TITLE
New feature: --pidfile

### ISSUE THREAD

**Issue by bjori** [10gen/mongo-orchestration#203]
mongo-orchestration writes the server.pid into the current working directory.
this makes restarting and even shutting down mongo-orchestration gracefully a pain.

Would be excellent if this directory/filename could be configured at startup, for example with --pidfile argument

    $ mongo-orchestration --pidfile /tmp/mo.pid

**Comment by llvtt** [comment]
added in 2c101194c711f44276baef71daa47a84bec92907
