### ISSUE TITLE
Option to set --enableMajorityReadConcern

### ISSUE THREAD

**Issue by ajdavis** [10gen/mongo-orchestration#207]
An option in Orchestration configs to turn on "--enableMajorityReadConcern" if and only if the server version is recent enough to support it, otherwise ignore the option. Makes it easier to do configs for matrix builds.

**Comment by llvtt** [comment]
It would be easier just to have this always switched on, if the server supports it. Is there any reason to have this be configurably turned on/off?

**Comment by bjori** [comment]
Yes. Making sure we support configurations that do not have it enabled, but
yet report wire_version = 4.

**Comment by llvtt** [comment]
resolved via #208
