### ISSUE TITLE
Detect when mongod or mongos quits early

### ISSUE THREAD

**Issue by ajdavis** [10gen/mongo-orchestration#209]
If you pass an unrecognized config option to a mongod or mongos, or if disk is already full when they start, or various other misconfigurations, the mongod or mongos processes that Orchestration starts will exit quickly with nonzero code.

Orchestration should detect this, clean up, and return a useful error to the caller, rather than waiting 120 seconds to decide that starting the cluster has generically "timed out".

**Comment by ShaneHarvey** [comment]
Note we should also address the stdout/stderr issues described in https://github.com/10gen/mongo-orchestration/issues/272 when fixing this issue.

**Comment by ShaneHarvey** [comment]
This was fixed by #280
