### ISSUE TITLE
SERVER-22663 will require --shardsvr for mongod used in a shard

### ISSUE THREAD

**Issue by xdg** [10gen/mongo-orchestration#218]
Not sure if this impacts mongo-orchestration, but it broke the Perl driver's orchestration, so this is FYI.

**Comment by bjori** [comment]
{code}
[2016/08/12 22:17:00.122] FAIL:tests/test-write-commands.c:64  test_split_insert()
[2016/08/12 22:17:00.122]   r
[2016/08/12 22:17:00.122]   Multiple write errors: "Cannot accept sharding commands if not started with --shardsvr", "Cannot accept sharding commands if not started with --shardsvr", "Cannot accept sharding commands if not started with --shardsvr"
{code}


I started seeing this on Friday in a new matrix, guess it wasn't my fault!

**Comment by behackett** [comment]
Yep, this is needed in Jenkins now as well.

**Comment by behackett** [comment]
That didn't completely fix the problem.

**Comment by behackett** [comment]
Actually, that did fix it. Jenkins was deceiving me.

**Comment by dscaravaggi** [comment]
I need to add --shardsvr in 3.6.3

**Comment by ShaneHarvey** [comment]
@dscaravaggi  Mongo-orchestration should automatically add the shardsvr flag. Can you post your mongo-orchestration version and your cluster config?

**Comment by dscaravaggi** [comment]
@ShaneHarvey Ops...  I realized that mongo-orchestration is not directly linked to official mongodb site recipes. In any case next time I have to manage another sharded cluster pool I will use with mongo-orchestration from the beginning.  Thanks
