### ISSUE TITLE
server.await_connection fails with IPv6 localhost

### ISSUE THREAD

**Issue by gurudave** [10gen/mongo-orchestration#237]
I was seeing a failure starting mongo-orchestration straight out the box. It reported that it failed to connection after 5 attempts, but I found that the server was definitely running.

What I found was that when the socket was bound, it was picking IPv6 localhost for the bind address:

`Insomnia:lightning dave$ netstat -an | grep 8889`
`tcp6       0      0  ::1.8889               *.*                    LISTEN     `

However await_connection specifies socket.AF_INET, which forces an IPv4 connection, and therefore it fails to connect ([Errno 61] Connection refused). I got it to work by specifying '-b 127.0.0.1' on the command line, but I guess there must be a better solution than that.

This occurred on macOS 10.13.2. Hope the description makes sense. I can provide more details if not!

**Comment by ShaneHarvey** [comment]
Thanks for reporting this! I see how this is a problem. Instead of using AF_INET and then calling connect we should probably use [socket.create_connection](https://docs.python.org/2/library/socket.html#socket.create_connection) instead.

**Comment by jaraco** [comment]
I have this problem also, encountered when attempting to run tests in mongo-connector. Thanks for suggesting `socket.create_connection`. I was unaware of that function.
