### ISSUE TITLE
Support starting MongoDB 3.4+ with compression

### ISSUE THREAD

**Issue by behackett** [10gen/mongo-orchestration#245]
Drivers are supposed to support wire protocol with MongoDB 3.4 and newer. MongoOrchestration should support starting MongoDB 3.4 with snappy compression support and 3.6+ with snappy and zlib support.

I'm somewhat indifferent to this being a completely separate config, or a default for these server versions.

**Comment by ShaneHarvey** [comment]
I think this was already done in https://github.com/10gen/mongo-orchestration/pull/233.

**Comment by behackett** [comment]
Huh, I guess I missed this. Are there config files that use it already?

**Comment by ShaneHarvey** [comment]
It automatically adds "networkMessageCompressors" like this:
https://github.com/ShaneHarvey/mongo-orchestration/blob/master/mongo_orchestration/servers.py#L80-L88

Configs don't need to specifiy it manually.

**Comment by behackett** [comment]
Oh. That should have been obvious in the original patch. Thanks!
