### ISSUE TITLE
Starting a replica set on Travis failed

### ISSUE THREAD

**Issue by sandrokeil** [10gen/mongo-orchestration#249]
I've tried different replica set config files without success. Most of the files produces the error `id field not found in configuration file`. Even if I set the id in the configuration file, the HTTP response is 404. Are there any examples how to start a MongoDB replica set in Travis via `.travis.yml`?

Here is the [Travis report](https://travis-ci.org/prooph/event-store-mongodb-adapter/jobs/402283636#L616) and here the [travis.yml](https://github.com/sandrokeil/event-store-mongodb-adapter/blob/feature/support-mongodb-4-0/.travis.yml#L60) file.

**Comment by ShaneHarvey** [comment]
Hi @sandrokeil, please check out the example configurations in https://github.com/10gen/mongo-orchestration/tree/master/mongo_orchestration/configurations

You can also see how the PHP driver uses mongo-orchestration on Travis: https://github.com/mongodb/mongo-php-driver/blob/master/.travis.yml
