### ISSUE TITLE
SCRAM-SHA-256 (and more)

### ISSUE THREAD

**Issue by Neustradamus** [10gen/mongo-orchestration#260]
Ready for SCRAM-SHA-256 (and more)?

**Comment by Neustradamus** [comment]
In the code, there is only SCRAM-SHA-1:
- https://github.com/10gen/mongo-orchestration/blob/master/mongo_orchestration/sharded_clusters.py
- https://github.com/10gen/mongo-orchestration/blob/master/mongo_orchestration/common.py

**Comment by behackett** [comment]
I see. I think we can remove those restrictions now. We currently restrict mongo-orchestration to PyMongo <3.6 for reasons that were resolved some time ago. 3.7 added SCRAM-SHA-256. That said, there are no know security issues with SCRAM-SHA-1. Using SHA-1 in SCRAM is not even remotely the same as signing TLS certs with SHA-1.

**Comment by Neustradamus** [comment]
@behackett: Any news?
