### ISSUE TITLE
m-o does not provision clusters that require tls verification

### ISSUE THREAD

**Issue by p-mongo** [10gen/mongo-orchestration#271]
According to my reading of m-o source, it always launches clusters with ` --sslWeakCertificateValidation`. This means clusters provisioned by m-o are not suitable for testing end to end TLS verification, such as https://jira.mongodb.org/browse/RUBY-1794.

**Comment by ShaneHarvey** [comment]
The "stock" configs that are in [drivers-evergreen-tools](https://github.com/mongodb-labs/drivers-evergreen-tools/blob/master/.evergreen/orchestration/configs/servers/basic-ssl.json#L15) always set `sslWeakCertificateValidation=true` but I don't think MO always adds sslWeakCertificateValidation.

**Comment by p-mongo** [comment]
Okay that's good to hear. If one then wanted to have full certificate verification configured, what are the steps to achieve that?

**Comment by ShaneHarvey** [comment]
Simple example:
```
$ cat ssl.json
{
	"name" : "mongod",
	"procParams" : {
		"bind_ip" : "127.0.0.1,::1",
		"ipv6" : true,
		"logappend" : true,
		"port" : 27017,
		"setParameter" : {
			"enableTestCommands" : 1
		}
	},
	"sslParams" : {
		"sslCAFile" : "/Users/shane/git/mongo-python-driver/test/certificates/ca.pem",
		"sslOnNormalPorts" : true,
		"sslPEMKeyFile" : "/Users/shane/git/mongo-python-driver/test/certificates/server.pem"
	}
}
$ curl -XPUT http://localhost:8889/v1/servers/server_id -d@ssl.json
{"mongodb_uri": "mongodb://localhost:27017", "statuses": {"primary": true, "mongos": false}, "serverInfo": {"version": "4.2.0-rc0", "gitVersion": "f17ad42fb53a2b5ae224006fa8f36c531e6f0b04", ...                                                                                                                                                                      
```

**Comment by p-mongo** [comment]
Thank you Shane. My understanding is that, since drivers' test suites use drivers-evergreen-tools to drive m-o, this sample code is not something I can directly use in a driver test suite. Is this a correct assessment?

**Comment by ShaneHarvey** [comment]
You are free to add your own files to drivers-evergreen-tools :)

**Comment by ShaneHarvey** [comment]
I just recently added https://github.com/mongodb-labs/drivers-evergreen-tools/blob/master/.evergreen/orchestration/configs/servers/disableTestCommands.json for the python driver.

**Comment by ShaneHarvey** [comment]
Closing since this isn't a problem with MO.
